branch-defaults:
  master:
    environment: experiment-dev
    group_suffix: null
deploy:
  artifact: target/application.jar
global:
  application_name: experiment
  branch: null
  default_ec2_keyname: null
  default_platform: Java
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
